In [88]:
#2.1 Gaussian Elimination

'''Question 1: Put together the code for "naive" Gaussian elimination (meaning no row exchanges allowed)'''

import numpy as np
from scipy.sparse.linalg import cg
import scipy.linalg as la

def forward_elimination(A, b, n):
    """
    Calculates the forward part of Gaussian elimination.
    """
    for row in range(0, n-1):
        for i in range(row+1, n):
            factor = A[i,row] / A[row,row]
            for j in range(row, n):
                A[i,j] = A[i,j] - factor * A[row,j]

            b[i] = b[i] - factor * b[row]

        print('A = \n%s \nand b = %s' % (A,b))
    return A, b

def back_substitution(a, b, n):
    """"
    Does back substitution, returns the Gauss result.  
    """
    x = np.zeros((n,1))
    x[n-1] = b[n-1] / a[n-1, n-1]
    for row in range(n-2, -1, -1):
        sums = b[row]
        for j in range(row+1, n):
            sums = sums - a[row,j] * x[j]
        x[row] = sums / a[row,row]
    return x

def naive_gauss_elimination(A, b):
    """
    This function performs Gauss elimination without pivoting.
    """
    n = A.shape[0]  # n rows

    # Check for zero diagonal elements
    if any(np.diag(A)==0):
        raise ZeroDivisionError(('Division by zero will occur; '
                                  'pivoting currently not supported'))

    forward_elimination(A, b, n)
    return back_substitution(A, b, n)

# Main program starts here

A = np.array([[2,   -2,   -1],
                      [4,   1,  -2],
                      [-2,   1, -1]])
b = np.array([-2, 1, -3])
x = naive_gauss_elimination(A, b)
print('Gauss result is x = \n %s' % x)

A2 = np.array([[1,   2,   -1],
                      [0,   3,  1],
                      [2,   -1,  1]])
b2 = np.array([2, 4, 2])
x2 = naive_gauss_elimination(A2,b2)
print('Gauss result is x = \n %s' %x2)

A3 = np.array([[1,   -1,   1],
                      [2,   1,  -4],
                      [-1,   3,  -2]])
b3 = np.array([-2, -7, 6])
x3 = naive_gauss_elimination(A3,b3)
print('Gauss result is x = \n %s' %x3)

'''Question 2: Let H denoate the n x n Hilbert Matrix, whose (i,j) entry is 1/(i + j -1). Use the naive gaussian elimination algorithm to 
    solve Hx = b, where b is the vector of all ones for n = 2 and n = 5'''

# Hilbert matrix when n = 2 so it's a 2 x 2 Hilbert matrix

Hilbert = np.array([[1,   1/2],
                      [1/2,   1/3]])
Hilbert_b = np.array([1, 1])
x4 = naive_gauss_elimination(Hilbert,Hilbert_b)
print('Gauss result is x = \n %s' %x4)

# Hilbert matrix when n = 5 so it's a 5 x 5 Hilbert matrix

Hilbert2 = np.array([[1,   1/2,   1/3,   1/4,  1/5],
                      [1/2,   1/3,  1/4,  1/5,  1/6],
                      [1/3,   1/4,  1/5,  1/6,  1/7],
                      [1/4,  1/5,   1/6,  1/7,  1/8],
                      [1/5, 1/6,  1/7,  1/8,  1/9]])
Hilbert_b2 = np.array([1, 1, 1, 1, 1])
x5 = naive_gauss_elimination(Hilbert2,Hilbert_b2)
print('Gauss result is x = \n %s' %x5)

A = 
[[ 2 -2 -1]
 [ 0  5  0]
 [ 0 -1 -2]] 
and b = [-2  5 -5]
A = 
[[ 2 -2 -1]
 [ 0  5  0]
 [ 0  0 -2]] 
and b = [-2  5 -4]
Gauss result is x = 
 [[ 1.]
 [ 1.]
 [ 2.]]
A = 
[[ 1  2 -1]
 [ 0  3  1]
 [ 0 -5  3]] 
and b = [ 2  4 -2]
A = 
[[ 1  2 -1]
 [ 0  3  1]
 [ 0  0  4]] 
and b = [2 4 4]
Gauss result is x = 
 [[ 1.]
 [ 1.]
 [ 1.]]
A = 
[[ 1 -1  1]
 [ 0  3 -6]
 [ 0  2 -1]] 
and b = [-2 -3  4]
A = 
[[ 1 -1  1]
 [ 0  3 -6]
 [ 0  0  3]] 
and b = [-2 -3  6]
Gauss result is x = 
 [[-1.]
 [ 3.]
 [ 2.]]
A = 
[[ 1.          0.5       ]
 [ 0.          0.08333333]] 
and b = [1 0]
Gauss result is x = 
 [[ 1.]
 [ 0.]]
A = 
[[ 1.          0.5         0.33333333  0.25        0.2       ]
 [ 0.          0.08333333  0.08333333  0.075       0.06666667]
 [ 0.          0.08333333  0.08888889  0.08333333  0.07619048]
 [ 0.          0.075       0.08333333  0.08035714  0.075     ]
 [ 0.          0.06666667  0.07619048  0.075       0.07111111]] 
and b = [1 0 0 0 0]
A = 
[[  1.00000000e+00   5.00000000e-01   3.

In [89]:
# Section 2.2 LU Factorization
    
def mylu(A):
    """
    This function performs the LU factorization method.
    """
    n = A.shape[0]  # dimension of matrix

    # Check for zero diagonal elements
    if any(np.diag(A)==0):
        raise ZeroDivisionError(('Division by zero will occur; '
                                  'pivoting currently not supported'))
    print("A = \n%s" %A)

    lu_factorization(A, n)
    
def lu_factorization(A, n):
    """
    Calculates lower identity matrix and upper triangular matrix.
    """
    identity = np.mat(np.eye(n))  # create a n x n identity matrix
    for row in range(0, n-1):
        for i in range(row+1, n):
            identity[i,row] = A[i,row]/A[row,row] 
            for j in range(row+1, n):
                A[i,j] = A[i,j] - identity[i,row] * A[row,j]
    upper_triangular = np.triu(A,0) # get the upper triangular matrix 

    print('L = \n%s \n U =\n %s' % (identity,upper_triangular))

print("(a)")
A = np.array([[3,   1,   2],
                      [6,   3,  4],
                      [3,   1, 5]])
mylu(A)

print("(b)")
A2 = np.array([[4,   2,   0],
                      [4,   4,  2],
                      [2,   2, 3]])
mylu(A2)

print("(c)")
A3 = np.array([[1,  -1,  1,  2],
                      [0,  2,  1,  0],
                      [1,  3, 4,  4],
                      [0,  2,  1,  -1]])
mylu(A3)


def Axb(A, b):
    
    n = A.shape[0]  # dimension of matrix

    # Check for zero diagonal elements
    if any(np.diag(A)==0):
        raise ZeroDivisionError(('Division by zero will occur; '
                                  'pivoting currently not supported'))
    
    b = np.vstack(b)
    print("A = \n%s" %A)
    print("b = \n%s" %b)
    solveAxb(A, b, n)
    
def solveAxb(A, b, n):
    '''
    calculate the forward and backward substitution to solve for the x matrix
    '''
    identity = np.mat(np.eye(n))  # create a n x n identity matrix
    for j in range(1, n-1):
        for i in range(j+1, n):
            identity[i,j] = A[i,j]/A[j,j] 
            for k in range(j+1, n):
                A[i,k] = A[i,k] - identity[i,j] * A[j,k]
    
    c = np.zeros((n,1))
    #c[n-1] = b[n-1] / A[n-1, n-1]
    for i in range(1,n):
        for j in range(1,i-1):
            c[i] = c[i] + identity[i,j] * c[j]
        c[i] = b[i] - c[i]
    
    x = np.zeros((n,1))
    #x[n-1] = b[n-1] / A[n-1, n-1]
    for i in range(n-2, -1, -1):
        for j in range(i+1,n):
            c[i] = c[i] - A[i,j] * x[j]
        x[i] = c[i]/A[i,i]

    print('x = \n%s' % x)
        

A4 = np.array([[4,   2,   0],
                      [4,   4,  2],
                      [2,   2, 3]])
b = np.array([2, 4, 6])
#Axb(A4,b)

print ("Solutions:\n",np.linalg.solve(A4, b)) #built-in function in numpy to calculate Ax=b with LU factorization

(a)
A = 
[[3 1 2]
 [6 3 4]
 [3 1 5]]
L = 
[[ 1.  0.  0.]
 [ 2.  1.  0.]
 [ 1.  0.  1.]] 
 U =
 [[3 1 2]
 [0 1 0]
 [0 0 3]]
(b)
A = 
[[4 2 0]
 [4 4 2]
 [2 2 3]]
L = 
[[ 1.   0.   0. ]
 [ 1.   1.   0. ]
 [ 0.5  0.5  1. ]] 
 U =
 [[4 2 0]
 [0 2 2]
 [0 0 2]]
(c)
A = 
[[ 1 -1  1  2]
 [ 0  2  1  0]
 [ 1  3  4  4]
 [ 0  2  1 -1]]
L = 
[[ 1.  0.  0.  0.]
 [ 0.  1.  0.  0.]
 [ 1.  2.  1.  0.]
 [ 0.  1.  0.  1.]] 
 U =
 [[ 1 -1  1  2]
 [ 0  2  1  0]
 [ 0  0  1  2]
 [ 0  0  0 -1]]
Solutions:
 [ 1. -1.  2.]


In [90]:
#2.5 Iterative Method using Jacobi Method and Gauss-Seidel 
def jacobi(A, b, x, n):

    D = np.diag(A)
    R = A - np.diagflat(D)
    
    for i in range(n):
        x = (b - np.dot(R,x))/ D
        print (str(i+1))
        print(x)
    return x

A = np.array([[2, -1, 0], [-1, 2, -1], [0, -1, 2]])
b = [0, 2, 0]
x = [0, 0, 0] # initial values
n = 2 #number of iterations

x = jacobi(A, b, x, n)
#print (x)

def gauss_seidel(A, b, x, n):

    L = np.tril(A)
    U = A - L
    for i in range(n):
        x = np.dot(np.linalg.inv(L), (b - np.dot(U, x)))
        print (str(i+1))
        print(x)
    return x


A2 = np.array([[2, -1, 0], [-1, 2, -1], [0, -1, 2]])
b2 = [0, 2, 0]
x2 = [0, 0, 0]

n2 = 20

y = gauss_seidel(A2, b2, x2, n2)

1
[ 0.  1.  0.]
2
[ 0.5  1.   0.5]
1
[ 0.   1.   0.5]
2
[ 0.5   1.5   0.75]
3
[ 0.75   1.75   0.875]
4
[ 0.875   1.875   0.9375]
5
[ 0.9375   1.9375   0.96875]
6
[ 0.96875   1.96875   0.984375]
7
[ 0.984375   1.984375   0.9921875]
8
[ 0.9921875   1.9921875   0.99609375]
9
[ 0.99609375  1.99609375  0.99804688]
10
[ 0.99804688  1.99804688  0.99902344]
11
[ 0.99902344  1.99902344  0.99951172]
12
[ 0.99951172  1.99951172  0.99975586]
13
[ 0.99975586  1.99975586  0.99987793]
14
[ 0.99987793  1.99987793  0.99993896]
15
[ 0.99993896  1.99993896  0.99996948]
16
[ 0.99996948  1.99996948  0.99998474]
17
[ 0.99998474  1.99998474  0.99999237]
18
[ 0.99999237  1.99999237  0.99999619]
19
[ 0.99999619  1.99999619  0.99999809]
20
[ 0.99999809  1.99999809  0.99999905]


In [101]:
#2.6 Methods for Symmetric positive-definite matrices

# Conjugate Gradient Method
A3 = np.array([[1, 2], [2, 5]])
b3 = [1, 1]
print(cg(A3, b3))

A3 = np.array([[1, 0], [0, 2]])
b3 = [2, 4]
print(cg(A3, b3))


# Cholesky method
def cholesky(A):
    L = [[0.0] * len(A) for _ in range(len(A))]
    for i, (Ai, Li) in enumerate(zip(A, L)):
        for j, Lj in enumerate(L[:i+1]):
            s = sum(Li[k] * Lj[k] for k in range(j))
            Li[j] = np.sqrt(Ai[i] - s) if (i == j) else \
                      (1.0 / Lj[j] * (Ai[j] - s))
    return L
A5 = np.array([[25, 5], [5, 26]])
print(np.transpose(cholesky(A5)))

L2 = la.cholesky(A5)
print(np.dot(L2.T, L2))

print(L2)
print(A5)

# solve the cholesky facotirzation of A to solve for x
A6 = np.array([[1, -1], [-1, 5]])
b6 = [3, -7]

c, low = la.cho_factor(A6)
x = la.cho_solve((c, low), b6)
print(x)

(array([ 3., -1.]), 0)
(array([ 2.,  2.]), 0)
[[ 5.  1.]
 [ 0.  5.]]
[[ 25.   5.]
 [  5.  26.]]
[[ 5.  1.]
 [ 0.  5.]]
[[25  5]
 [ 5 26]]
[ 2. -1.]
