In [42]:
#2.1 Gaussian Elimination

'''Question 1: Put together the code for "naive" Gaussian elimination (meaning no row exchanges allowed)'''

import numpy as np

def forward_elimination(A, b, n):
    """
    Calculates the forward part of Gaussian elimination.
    """
    for row in range(0, n-1):
        for i in range(row+1, n):
            factor = A[i,row] / A[row,row]
            for j in range(row, n):
                A[i,j] = A[i,j] - factor * A[row,j]

            b[i] = b[i] - factor * b[row]

        print('A = \n%s \nand b = %s' % (A,b))
    return A, b

def back_substitution(a, b, n):
    """"
    Does back substitution, returns the Gauss result.  
    """
    x = np.zeros((n,1))
    x[n-1] = b[n-1] / a[n-1, n-1]
    for row in range(n-2, -1, -1):
        sums = b[row]
        for j in range(row+1, n):
            sums = sums - a[row,j] * x[j]
        x[row] = sums / a[row,row]
    return x

def naive_gauss_elimination(A, b):
    """
    This function performs Gauss elimination without pivoting.
    """
    n = A.shape[0]  # n rows

    # Check for zero diagonal elements
    if any(np.diag(A)==0):
        raise ZeroDivisionError(('Division by zero will occur; '
                                  'pivoting currently not supported'))

    forward_elimination(A, b, n)
    return back_substitution(A, b, n)

# Main program starts here

A = np.array([[2,   -2,   -1],
                      [4,   1,  -2],
                      [-2,   1, -1]])
b = np.array([-2, 1, -3])
x = naive_gauss_elimination(A, b)
print('Gauss result is x = \n %s' % x)

A2 = np.array([[1,   2,   -1],
                      [0,   3,  1],
                      [2,   -1,  1]])
b2 = np.array([2, 4, 2])
x2 = naive_gauss_elimination(A2,b2)
print('Gauss result is x = \n %s' %x2)

A3 = np.array([[1,   -1,   1],
                      [2,   1,  -4],
                      [-1,   3,  -2]])
b3 = np.array([-2, -7, 6])
x3 = naive_gauss_elimination(A3,b3)
print('Gauss result is x = \n %s' %x3)

'''Question 2: Let H denoate the n x n Hilbert Matrix, whose (i,j) entry is 1/(i + j -1). Use the naive gaussian elimination algorithm to 
    solve Hx = b, where b is the vector of all ones for n = 2 and n = 5'''

# Hilbert matrix when n = 2 so it's a 2 x 2 Hilbert matrix

Hilbert = np.array([[1,   1/2],
                      [1/2,   1/3]])
Hilbert_b = np.array([1, 1])
x4 = naive_gauss_elimination(Hilbert,Hilbert_b)
print('Gauss result is x = \n %s' %x4)

# Hilbert matrix when n = 5 so it's a 5 x 5 Hilbert matrix

Hilbert2 = np.array([[1,   1/2,   1/3,   1/4,  1/5],
                      [1/2,   1/3,  1/4,  1/5,  1/6],
                      [1/3,   1/4,  1/5,  1/6,  1/7],
                      [1/4,  1/5,   1/6,  1/7,  1/8],
                      [1/5, 1/6,  1/7,  1/8,  1/9]])
Hilbert_b2 = np.array([1, 1, 1, 1, 1])
x5 = naive_gauss_elimination(Hilbert2,Hilbert_b2)
print('Gauss result is x = \n %s' %x5)

A = 
[[ 2 -2 -1]
 [ 0  5  0]
 [ 0 -1 -2]] 
and b = [-2  5 -5]
A = 
[[ 2 -2 -1]
 [ 0  5  0]
 [ 0  0 -2]] 
and b = [-2  5 -4]
Gauss result is x = 
 [[ 1.]
 [ 1.]
 [ 2.]]
A = 
[[ 1  2 -1]
 [ 0  3  1]
 [ 0 -5  3]] 
and b = [ 2  4 -2]
A = 
[[ 1  2 -1]
 [ 0  3  1]
 [ 0  0  4]] 
and b = [2 4 4]
Gauss result is x = 
 [[ 1.]
 [ 1.]
 [ 1.]]
A = 
[[ 1 -1  1]
 [ 0  3 -6]
 [ 0  2 -1]] 
and b = [-2 -3  4]
A = 
[[ 1 -1  1]
 [ 0  3 -6]
 [ 0  0  3]] 
and b = [-2 -3  6]
Gauss result is x = 
 [[-1.]
 [ 3.]
 [ 2.]]
A = 
[[ 1.          0.5       ]
 [ 0.          0.08333333]] 
and b = [1 0]
Gauss result is x = 
 [[ 1.]
 [ 0.]]
A = 
[[ 1.          0.5         0.33333333  0.25        0.2       ]
 [ 0.          0.08333333  0.08333333  0.075       0.06666667]
 [ 0.          0.08333333  0.08888889  0.08333333  0.07619048]
 [ 0.          0.075       0.08333333  0.08035714  0.075     ]
 [ 0.          0.06666667  0.07619048  0.075       0.07111111]] 
and b = [1 0 0 0 0]
A = 
[[  1.00000000e+00   5.00000000e-01   3.